version: '3.9'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    networks:
      - wastewatch-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin@4040
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  nodejs-app:
    build: .
    container_name: wastewatch-app
    networks:
      - wastewatch-network
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://admin:Admin%404040@mongodb:27017/waste_management_system?authSource=admin
    depends_on:
      - mongodb

networks:
  wastewatch-network:

volumes:
  mongodb_data:
